Minor fixes
equinor/lcm pull request #106
Opened 2021-02-09 08:56 UTC by KristianKjerstad

- round bridge values to one decimal
- added total score to radar chart
- change default pill volume to 1
- sum density for concentration blends

2021-02-09 10:08 UTC, soofstad requested changes
A few minor.
After that good to merge :+1:

2021-02-09 10:08 UTC, soofstad commented on api/calculators/bridge.py
> +    return [round(num, 1) for num in cumulative_curve]
How did this effect performance?
This is run in the fitness function (eg. many times)
Better to do this in the final response step

2021-02-09 10:08 UTC, soofstad commented on web/src/Components/Optimization/OptimizationRunner.tsx
>      mass: 3500,
This should be 350 now

2021-02-10 12:14 UTC, merged

2021-02-10 12:16 UTC, KristianKjerstad commented
closes #101 #103  #104 #105